spring:
  application:
    name: blog-backend
  profiles:
    active: ${activeProfile:dev}

springdoc:
  api-docs:
    path: /context-path/v3/api-docs
  swagger-ui:
    path: /context-path/swagger-ui.html