# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ThoughtLabs CI/CD Flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'
        cache: maven

    - name: Replaced application.yml with application-prod.yml
      run: |
        mv src/main/resources/application-prod.yml src/main/resources/application.yml
#        sed -i "s/spring.profiles.active:.*/spring.profiles.active: prod/g" src/main/resources/application.yml

    - name: Print application.yml
      run: |
        echo "CONTENT FOR application.yml"
        cat src/main/resources/application.yml

    - name: Update application.yml with secrets
      env:
        APP_SECRET: ${{secrets.APP_SECRET}}

        S3_ACCESS_KEY: ${{secrets.AWS_S3_ACCESSKEY}}
        S3_SECRET_KEY: ${{secrets.AWS_S3_SECRET}}

        GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
        GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}

        FACEBOOK_CLIENT_ID: ${{secrets.FACEBOOK_CLIENT_ID}}
        FACEBOOK_CLIENT_SECRET: ${{secrets.FACEBOOK_CLIENT_SECRET}}

      run: |
        sed -i "s#{appSecret}#${APP_SECRET}#g" src/main/resources/application-prod.yml

        sed -i "s#{s3AccessKey}#${S3_ACCESS_KEY}#g" src/main/resources/application-prod.yml
        sed -i "s#{s3SecretKey}#${S3_SECRET_KEY}#g" src/main/resources/application-prod.yml
        
        sed -i "s#{googleClientId}#${GOOGLE_CLIENT_ID}#g" src/main/resources/application-prod.yml
        sed -i "s#{googleClientSecret}#${GOOGLE_CLIENT_SECRET}#g" src/main/resources/application-prod.yml
        
        sed -i "s#{facebookClientId}#${FACEBOOK_CLIENT_ID}#g" src/main/resources/application-prod.yml
        sed -i "s#{facebookClientSecret}#${FACEBOOK_CLIENT_SECRET}#g" src/main/resources/application-prod.yml
        
        echo "CONTENT FOR application-prod.yml"
        cat src/main/resources/application-prod.yml

    - name: Build with Maven
      run: mvn -B package --file pom.xml
